### ISSUE TITLE
TATW async issue

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Pythonic-Rainbow/Big-Bang-Mods#14]
**Pack Version:**
https://github.com/Pythonic-Rainbow/Big-Bang-Mods/commit/63c3892ebc8224d20489a1c52fcc8c6de1832c92

**References(If you know about this issue, Put reference links below. If you don't, ignore this.**
https://versioned.temporary.solutions/AromasMods/TATW/issues/5

**Comment by 0x4B776F6B4353** [comment]
Will be fixed in future updates.

**Comment by Pythonic-Rainbow** [comment]
TATW will be in Beta branch starting from V15 until next release is available.

**Comment by Pythonic-Rainbow** [comment]
Should be fixed in https://github.com/TCLRainbow/Big-Bang-Mods/commit/e30a6da0d2c4aacc4734ce2085f1751f56505f6f
