### ISSUE TITLE
Gadgetry Transmission doesnt work

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [Pythonic-Rainbow/Big-Bang-Mods#17]
**Pack Version:**
Any
 

**Describe your problem(Use human-readable syntax!)**
Gadgetry Transmission is just broken
 

**References(If you know about this issue, Put reference links below. If you don't, ignore this.**
https://minecraft.curseforge.com/projects/gadgetry-transmission?comment=1

**Comment by Pythonic-Rainbow** [comment]
@CrankySupertoon01 thanks for your report!  As we know the mod isn't being updated by the mod author, I can do nothing about it. The mod doesn't do critical harm to overall performance of the modpack so I'll leave it alone , until the issue is resolved by the mod author.

**Comment by Pythonic-Rainbow** [comment]
EpicSquid is slowly updating the mod, however the progress is not optimistic.
This issue will be opened until the mod is dead or rewritten.

**Comment by Pythonic-Rainbow** [comment]
Even the mod authors have no idea what was happening, and things changed a lot since then, I have no way to trace the bug. Sorry but this issue is unsolvable.
