### ISSUE TITLE
Configure PlusTiC<->MoarTinkers

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Pythonic-Rainbow/Big-Bang-Mods#22]
> and I think I want to reconfigure MoarTinkers to be compatible with PlusTiC as well as to balance it

> What I told you about using both PlusTiC and MoarTinkers  - both of them add same materials in some instances
> I shall make a list and configure the mod accordingly

By @Twingrey

**Comment by Twingrey** [comment]
Issue is solved by tweaking config. The provided config files offer the best compatibility as well as balance.
[config.zip](https://github.com/TCLRainbow/Big-Bang-Mods/files/2430249/config.zip)
