### ISSUE TITLE
Thaumcraft<-x-> Forge 2767+

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Pythonic-Rainbow/Big-Bang-Mods#25]
https://github.com/Azanor/thaumcraft-beta/issues/1468

**Comment by Pokihead** [comment]
in the next Forge or Thaumcraft build? :D

**Comment by Pythonic-Rainbow** [comment]
@Pokihead next Thaumcraft build

**Comment by Pythonic-Rainbow** [comment]
Fixed in https://github.com/TCLRainbow/Big-Bang-Mods/commit/158f0b6a2a3cc3abd118df9a6dae04eb3330a028
