### ISSUE TITLE
PlusTiC Server Crash

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Pythonic-Rainbow/Big-Bang-Mods#30]
https://github.com/Landmaster/PlusTiC/issues/228

**Comment by Pythonic-Rainbow** [comment]
Downgrade implemented in https://github.com/TCLRainbow/Big-Bang-Mods/commit/fcda6de5037c30eff3304a60677027f5d0c92774

**Comment by Landmaster** [comment]
https://github.com/Landmaster/PlusTiC/commit/0ca0cc2ac3d3422f34bea3ecd99e05264df45e21 This can be closed, fixed in 6.5.4.1

**Comment by Pythonic-Rainbow** [comment]
Updated in https://github.com/TCLRainbow/Big-Bang-Mods/commit/6286217f65d57b4886aa848a669232e787e2df4a
