### ISSUE TITLE
Foamfix NoSuchField

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Pythonic-Rainbow/Big-Bang-Mods#35]
**Pack Version:**
1.12.2

**Describe your problem(Use human-readable syntax!)**
Server crash

**References(If you know about this issue, Put reference links below. If you don't, ignore this.**
https://github.com/asiekierka/FoamFix/issues/197

**Comment by Pythonic-Rainbow** [comment]
Appears on Client side when joining server

**Comment by Pythonic-Rainbow** [comment]
Downgrade to 0.10.3 fix it

**Comment by asiekierka** [comment]
Fixed in 0.10.5.

**Comment by Pythonic-Rainbow** [comment]
Thanks @asiekierka

**Comment by Pythonic-Rainbow** [comment]
Fixed in https://github.com/TCLRainbow/Big-Bang-Mods/commit/e7e595fefdba7c4bb68fd4d2360ae3c2f856e9b3
