### ISSUE TITLE
Mystical Agraddition Inferium seed T6 can't put in garden cloche

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Pythonic-Rainbow/Big-Bang-Mods#6]
**Pack Version:**
1.12.2 #11b

**References(If you know about this issue, Put reference links below. If you don't, ignore this.**
https://github.com/BlakeBr0/MysticalAgradditions/issues/33

**Comment by rlnt** [comment]
Can be fixed by this mod: https://www.curseforge.com/minecraft/mc-mods/mystagrad-cloche-compat

**Comment by Pythonic-Rainbow** [comment]
Implemented Relentless's fix in https://github.com/TCLRainbow/Big-Bang-Mods/commit/82bde88d6c8a206b9b01b0eff66b074cad501895
