### ISSUE TITLE
AE2 RV6 breaks Extra Cell

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Pythonic-Rainbow/Big-Bang-Mods#7]
**Pack Version:**
1.12.2 #12

**References(If you know about this issue, Put reference links below. If you don't, ignore this.**
https://github.com/ExtraCells/ExtraCells2/issues/578

**Comment by Pythonic-Rainbow** [comment]
Temporary solution:
Downgrade WirelessCraftingTerminal from Build 67 to 66
Downgrade AE2 to RV5
ExtraCell remains the latest.

**Comment by Pythonic-Rainbow** [comment]
Implemented in V14

**Comment by Pythonic-Rainbow** [comment]
With AE2 releasing RV6B1, EC2 seems to finally catch up RV6, we will test it in v3.1b2

EDIT: Awaiting EC2 to release their beta version for supporting RV6

**Comment by rlnt** [comment]
Applied Energistics released a full version today that's fixing this.

**Comment by Pythonic-Rainbow** [comment]
Full RV6 support implemented in https://github.com/TCLRainbow/Big-Bang-Mods/commit/52cdef6973da54082e525dc11b85c0ba2d49cc9d
